Change Python package from seamapi to seam. Get rid of yarn install.
seamapi/api-docs pull request #239
Opened 2024-01-27 05:15 UTC by DebbieAtSeam

2024-01-28 00:52 UTC, sybohy requested changes
Made a couple of changes; need to wait for @seveibar to deploy the python lib to the new name before we can merge this in

2024-01-28 00:52 UTC, sybohy commented on docs/seam-components/make-a-supported-devices-page-with-react.md
> -yarn add @seamapi/react
any reason why we're dropping yarn support?

2024-01-28 00:52 UTC, sybohy commented on docs/thermostats/get-thermostat.md
> +```javascript
```suggestion
```python
```

2024-01-28 00:55 UTC, DebbieAtSeam commented on docs/seam-components/make-a-supported-devices-page-with-react.md
> -yarn add @seamapi/react
@sybohy https://hello-seam.slack.com/archives/C01D0J9ACLF/p1705301765773369

2024-02-01 02:58 UTC, DebbieAtSeam commented on docs/seam-components/make-a-supported-devices-page-with-react.md
> -yarn add @seamapi/react
and https://hello-seam.slack.com/archives/C01D0J9ACLF/p1706726806980289

2024-06-18 19:29 UTC, closed without merging